### ISSUE TITLE
[auth extension]: extension shouldn't require service account details

### ISSUE THREAD

**Issue by cabljac** [MoralisWeb3/firebase-extensions#5]
Hi there, i'm reviewing these extensions for firebase.

I found an issue with your `auth` extension

Extensions shouldn't ask the developer for service account details during installation. Permissions for extensions can be added via roles. 

https://github.com/MoralisWeb3/firebase-extensions/blob/1b6f7cce90b18f270e665870d6a3d11fbbd07e74/auth/functions/src/index.ts#L21

Let me know if there's anything i can help with here.

**Comment by b4rtaz** [comment]
Not exactly. The extension requires `iam.serviceAccounts.signBlob` or `iam.serviceAccountTokenCreator` role to issue tokens. But those roles are restricted for extensions:

> Unfortunately, extensions cannot grant those roles. Signing blobs and creating SA tokens are pretty sensitive actions that have potential for abuse, so for security reasons we won't grant them automatically. // Joe Hanley, Sep 13, 2022

Check our discussion in the internal group for testers (`Create service account for extension with the "Service Account Token Creator" role`).

**Comment by b4rtaz** [comment]
Not exactly. The extension requires `iam.serviceAccounts.signBlob` or `iam.serviceAccountTokenCreator` role to issue tokens. But those roles are restricted for extensions. Check our discussion in the internal group (`Create service account for extension with the "Service Account Token Creator" role`).

**Comment by cabljac** [comment]
Where is this discussion sorry?

**Comment by b4rtaz** [comment]
I cannot link here.

**Comment by cabljac** [comment]
OK no worries, think i've found it

**Comment by joehan** [comment]
Hey @b4rtaz - I think there is a more secure approach you could take here. When you install an extension, we create a new service account for that extension. Ideally, users of your extension would manually grant the necessary role to that service account. If you test that out and it works for you, I'd suggest that you add instructions in POSTINSTALL.md explaining how to do so - something like:

```
This extension requires some extra set up after installation to work correctly.
1 - Go to https://console.cloud.google.com/iam-admin/iam?project=${PROJECT_ID}
2 - Click the `Grant Access` button
3 - In the principas box, put 'ext-${INSTANCE_ID}@${PROJECT_ID}.iam.gserviceaccount.com
4 - Select the role 'iam.serviceAccountTokenCreator'
5 - Click save.
```

The ${INSTANCE_ID} and ${PROJECT_ID} will automatically be replaced by the appropriate values when shown to users.

**Comment by b4rtaz** [comment]
Hi @joehan! Your approach doesn't work on the emulator. So a user cannot test the extension locally. This makes a development more difficult.

The current approach works everywhere.

**Comment by joehan** [comment]
Ahh, thats a good point (and I'm glad to hear that the emulator is helpful 😄.  The emulator uses your application default credentials (https://cloud.google.com/docs/authentication#service-accounts) when you make calls to prod services. I'm going to test this out myself to confirm, but I think you should be able to make the call successfully from the emulator if you set the application default credentials to a service account that has the required role.

**Comment by huangjeff5** [comment]
@b4rtaz Let's see if we can get it working on the emulator, can you tell me what happens if you try this?

1) Update code to use default credentials: `admin.initializeApp()`
2) Run this from the project root directory: `set GOOGLE_APPLICATION_CREDENTIALS=path\to\key.json` (ensure this account has the correct roles)
2) Start emulator and call local functions.

Also if you have a sample app / Moralis testing account, I'd be happy to try it out for you.

**Comment by b4rtaz** [comment]
Hi @huangjeff5! I've just tested your solution and it seems to work correctly. But I noticed several downsides:

* my whole application is running on the privileged account in the emulator, this seems to be dangerous,
* the local development is a bit more difficult (I need to set the environment variable every time when I want to run the emulator, of course I can set set this variable globally, but this is not a good idea if I work on multiple projects),
* a user has a completely different setup for the emulator and for the deploy (so it increases a "churn rate").

**Comment by b4rtaz** [comment]
@huangjeff5 @joehan can we close this issue for now?

**Comment by huangjeff5** [comment]
Hey Bart, yeah we can close it for now. FYI we are actively working with the Auth team to figure out a different solution that doesn't require the SA credentials, stay tuned for updates. We're really hoping we can find a workable way to launch your extension.

**Comment by b4rtaz** [comment]
Cool! Thanks for letting me know.
