### ISSUE TITLE
[streams extension]: How do I use the streams extension?

### ISSUE THREAD

**Issue by cabljac** [MoralisWeb3/firebase-extensions#6]
Is there a guide on how to use the streams extension? I installed it but it's not clear to me how to set it up with Moralis APIs

**Comment by b4rtaz** [comment]
Hi @cabljac!

We have a tutorial and video on YouTube:

* https://docs.moralis.io/streams-api/integrations/firebase
* https://www.youtube.com/watch?v=EieJVLhpvsI

**Comment by cabljac** [comment]
Thanks! Might be worth having these referenced in the POSTINSTALL.md, so users see them in the "Getting Started" section on firebase.

**Comment by b4rtaz** [comment]
We will add this soon.

**Comment by b4rtaz** [comment]
Hi @cabljac! I've just released new versions of `moralis-auth` and `moralis-streams` extensions. The new versions contain links to tutorials.

Can we close this issue?

**Comment by cabljac** [comment]
thanks!
