### ISSUE TITLE
[streams extension]: converts addresses to lowercase

### ISSUE THREAD

**Issue by cabljac** [MoralisWeb3/firebase-extensions#9]
Hi there,

While testing out your streams extension, I noticed that it converted my evm address to lowercase. If I understand correctly, evm addresses are case-insensitive, but casing can be used for checksum purposes.

Steps to reproduce:
- install extension and connect to Moralis stream (in prod) following tutorial
- trigger a stream event by making a transaction (sent Ether to MetaMask)

<img width="374" alt="Screenshot 2023-03-02 at 11 41 11" src="https://user-images.githubusercontent.com/32874567/222418795-8748c8ec-3f0c-4c32-b065-62f539c33123.png">

The diff of the addresses:

<img width="379" alt="Screenshot 2023-03-02 at 11 41 39" src="https://user-images.githubusercontent.com/32874567/222418892-1e1af713-9428-4219-9f71-7388aabcf1e2.png">

I'm not sure if this is intended behaviour? I thought I would raise an issue anyway in case.

**Comment by b4rtaz** [comment]
Hi @cabljac! Yes this an intended behavior. We wanted to reduce problems with address formatting. This is a common problem, at the app level an address can come from different sources (wallets, API, user input...). Sometimes it's uppercase... Sometimes lowercase... Sometimes mixed case (not always mixed in a correct way). By making it lowercase for all database records, a developer have a simple solution how to normalize an address to work with a database. Especially for database with case-sensitive data types like Firestore.

**Comment by cabljac** [comment]
Awesome OK. Everything else worked as expected :)
